version: 2.1

jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          # Update this line with the directory that contains your tests project file
          working_directory: ./Tests
          name: Build and Test
          command: |
            REPORTS_PATH=./test-reports
            dotnet restore
            dotnet build --configuration Release
            dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"nunit;LogFilePath=$REPORTS_PATH/junit.xml"
            find . -name junit.xml
      - store_artifacts:
          path: ./test-reports/junit.xml

workflows:
  default:
    jobs:
      - build-and-test
