version: 2.1

jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          name: Test
          command: |
            REPORTS_PATH=./test-reports
            dotnet restore
            dotnet build --configuration Release
            dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"nunit;LogFilePath=$REPORTS_PATH/junit.xml"
            pwd
            find . -name junit.xml
      - store_test_results:
          path: ./Tests/test-reports

workflows:
  default:
    jobs:
      - build-and-test
