version: 2.1

jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          name: Build
          command: |
            dotnet build --configuration Release
      - run:
          name: Test
          command: |
            dotnet test --no-build --configuration Release --logger:"junit;LogFilePath=./test-reports/results.xml"
      - store_test_results:
          path: ./Tests/test-reports
      - run:
          name: Package
          command: |
            dotnet pack --configuration Release
            mv Application/bin/Release/Application.*.nupkg /tmp/artifacts
            mv Library/bin/Release/Library.*.nupkg /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  default:
    jobs:
      - build-and-test
